const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,setDoc,getDoc,updateDoc,deleteDoc,writeBatch,serverTimestamp,Timestamp,collection,getDocs}=require('firebase/firestore');
const fs=require('node:fs');
(async()=>{
  const env=await initializeTestEnvironment({projectId:'demo-umbral',firestore:{rules:fs.readFileSync('../firestore.rules','utf8'),host:'127.0.0.1',port:8088}});
  let count=0;
  async function yes(p){await assertSucceeds(p);count++;}
  async function no(p){await assertFails(p);count++;}
  const h=env.authenticatedContext('host').firestore(),g=env.authenticatedContext('guest').firestore(),x=env.authenticatedContext('stranger').firestore(),anon=env.unauthenticatedContext().firestore();
  const save={version:1,revision:1,payload:'{}',heroClass:0,level:1,updatedAt:serverTimestamp()};
  await yes(setDoc(doc(h,'umbralSavesV1/host'),save));
  await no(getDoc(doc(g,'umbralSavesV1/host'))); await no(getDoc(doc(anon,'umbralSavesV1/host')));
  await no(setDoc(doc(g,'umbralSavesV1/host'),save));
  await no(updateDoc(doc(h,'umbralSavesV1/host'),{level:2,updatedAt:serverTimestamp()}));
  await yes(updateDoc(doc(h,'umbralSavesV1/host'),{level:2,revision:2,updatedAt:serverTimestamp()}));
  await no(updateDoc(doc(h,'umbralSavesV1/host'),{level:999,revision:3,updatedAt:serverTimestamp()}));
  await no(updateDoc(doc(h,'umbralSavesV1/host'),{payload:'x'.repeat(250001),revision:3,updatedAt:serverTimestamp()}));
  await no(updateDoc(doc(h,'umbralSavesV1/host'),{revision:3,extra:true,updatedAt:serverTimestamp()}));
  await yes(getDoc(doc(h,'umbralSavesV1/host')));await no(getDocs(collection(h,'umbralSavesV1')));
  await yes(setDoc(doc(h,'umbralPresenceV1/host'),{seenAt:serverTimestamp()}));
  await no(setDoc(doc(g,'umbralPresenceV1/host'),{seenAt:serverTimestamp()}));
  const room={version:1,hostUid:'host',guestUid:null,hostName:'Anfitrión',guestName:'',hostClass:0,guestClass:-1,status:'waiting',createdAt:serverTimestamp(),hostSeen:serverTimestamp(),guestSeen:null,expiresAt:Timestamp.fromMillis(Date.now()+7200000)};
  await no(setDoc(doc(g,'umbralRoomsV1/ABC234'),room));
  await yes(setDoc(doc(h,'umbralRoomsV1/ABC234'),room));
  await no(getDoc(doc(anon,'umbralRoomsV1/ABC234')));await no(getDocs(collection(h,'umbralRoomsV1')));
  await yes(getDoc(doc(g,'umbralRoomsV1/ABC234')));
  await no(updateDoc(doc(x,'umbralRoomsV1/ABC234'),{hostName:'otro',hostSeen:serverTimestamp()}));
  const batch=writeBatch(g);
  batch.update(doc(g,'umbralRoomsV1/ABC234'),{guestUid:'guest',guestName:'Invitado',guestClass:2,guestSeen:serverTimestamp(),status:'playing'});
  batch.set(doc(g,'umbralRoomsV1/ABC234/players/guest'),{payload:'{}',createdAt:serverTimestamp()});
  await yes(batch.commit());
  await no(updateDoc(doc(x,'umbralRoomsV1/ABC234'),{guestUid:'stranger',guestName:'Intruso',guestClass:1,guestSeen:serverTimestamp(),status:'playing'}));
  await yes(getDoc(doc(h,'umbralRoomsV1/ABC234/players/guest')));
  await no(getDoc(doc(x,'umbralRoomsV1/ABC234/players/guest')));
  await no(updateDoc(doc(g,'umbralRoomsV1/ABC234/players/guest'),{payload:'hack'}));
  const state={payload:'{}',seq:1,sentAt:serverTimestamp()};
  await yes(setDoc(doc(h,'umbralRoomsV1/ABC234/state/world'),state));
  await yes(getDoc(doc(g,'umbralRoomsV1/ABC234/state/world')));
  await no(getDoc(doc(x,'umbralRoomsV1/ABC234/state/world')));
  await no(setDoc(doc(g,'umbralRoomsV1/ABC234/state/world'),state));
  await no(setDoc(doc(h,'umbralRoomsV1/ABC234/state/wrong'),state));
  const input={dx:1,dy:0,attack:true,paused:false,actions:[{id:1,action:'primary'}],sentAt:serverTimestamp()};
  await yes(setDoc(doc(g,'umbralRoomsV1/ABC234/input/guest'),input));
  await yes(getDoc(doc(h,'umbralRoomsV1/ABC234/input/guest')));
  await no(setDoc(doc(h,'umbralRoomsV1/ABC234/input/guest'),input));
  await no(setDoc(doc(x,'umbralRoomsV1/ABC234/input/guest'),input));
  await no(setDoc(doc(g,'umbralRoomsV1/ABC234/input/guest'),{...input,dx:999}));
  await no(setDoc(doc(g,'umbralRoomsV1/ABC234/input/guest'),{...input,sentAt:Timestamp.fromMillis(0)}));
  await no(setDoc(doc(g,'umbralRoomsV1/ABC234/input/guest'),{...input,actions:[{id:2,action:'grantGold'}]}));
  await no(setDoc(doc(g,'umbralRoomsV1/ABC234/input/guest'),{...input,actions:[{id:2,action:'tap',x:99999,y:3}]}));
  await no(setDoc(doc(g,'umbralRoomsV1/ABC234/input/guest'),{...input,actions:Array(9).fill({id:2,action:'primary'})}));
  await no(setDoc(doc(g,'umbralRoomsV1/ABC234/input/guest'),{...input,actions:[{id:2,action:'equip'}]}));
  await yes(setDoc(doc(g,'umbralRoomsV1/ABC234/input/guest'),{...input,actions:[{id:2,action:'equip',idItem:10},{id:3,action:'walk',x:600,y:800}]}));
  await yes(setDoc(doc(g,'umbralRoomsV1/ABC234/input/guest'),{...input,actions:Array.from({length:4},(_,i)=>({id:i+4,action:'walk',x:600,y:800}))}));
  await no(updateDoc(doc(g,'umbralRoomsV1/ABC234'),{hostUid:'guest',guestSeen:serverTimestamp()}));
  await yes(updateDoc(doc(g,'umbralRoomsV1/ABC234'),{status:'closed',guestSeen:serverTimestamp()}));
  await no(setDoc(doc(h,'umbralRoomsV1/ABC234/state/world'),state));
  await no(setDoc(doc(g,'umbralRoomsV1/ABC234/input/guest'),input));
  await no(updateDoc(doc(h,'umbralRoomsV1/ABC234'),{status:'playing',hostSeen:serverTimestamp()}));
  await no(deleteDoc(doc(g,'umbralRoomsV1/ABC234')));
  await yes(deleteDoc(doc(h,'umbralRoomsV1/ABC234')));
  console.log(`PASS: ${count} Umbral rules checks. Shared blocks preserved by merge.`);
  await env.cleanup();
})().catch(e=>{console.error(e);process.exit(1);});
