const {chromium} = require('playwright');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({headless:true, channel:'msedge'});
  const page = await browser.newPage({viewport:{width:1280,height:820},deviceScaleFactor:1});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const out = path.resolve(__dirname,'../releases');
  fs.mkdirSync(out,{recursive:true});
  await page.goto('http://localhost:8174', {waitUntil:'networkidle'});
  // Flutter exposes semantic nodes after the accessibility placeholder is activated.
  const placeholder = page.locator('flt-semantics-placeholder');
  await placeholder.waitFor({state:'attached', timeout:60000});
  await placeholder.evaluate(el => el.click());
  await page.getByRole('button', {name:'Comenzar aventura'}).waitFor({timeout:60000});
  await page.screenshot({path:path.join(out,'umbral-home.png')});
  await page.getByRole('button', {name:'Comenzar aventura'}).click();
  await page.getByRole('button', {name:'Mochila [I]'}).waitFor();
  await page.screenshot({path:path.join(out,'umbral-refugio.png')});
  await page.keyboard.down('d');
  await page.waitForTimeout(4900);
  await page.keyboard.up('d');
  await page.keyboard.press('f');
  await page.waitForTimeout(200);
  await page.keyboard.down('d');
  await page.waitForTimeout(1200);
  await page.keyboard.up('d');
  await page.keyboard.press('m');
  await page.getByRole('button',{name:'Volver al juego'}).waitFor();
  await page.screenshot({path:path.join(out,'umbral-map.png')});
  const save = await page.evaluate(() => {
    const value = JSON.parse(localStorage.getItem('flutter.umbral.save.v1'));
    return typeof value === 'string' ? JSON.parse(value) : value;
  });
  if (save.zone !== 1 || !save.portals.includes(1)) throw new Error('Walking, zone gate or portal discovery failed: '+JSON.stringify(save.position));
  await page.getByRole('checkbox',{name:'Refugio del Alba'}).click();
  await page.getByRole('button',{name:'Viajar a Refugio del Alba'}).click();
  await page.keyboard.press('m');
  await page.getByRole('checkbox',{name:'Bosque de espinas'}).click();
  await page.getByRole('button',{name:'Viajar a Bosque de espinas'}).click();
  await page.keyboard.down('d');
  await page.keyboard.down(' ');
  await page.waitForTimeout(1000);
  await page.keyboard.up('d');
  await page.keyboard.press('q');
  await page.waitForTimeout(800);
  await page.keyboard.up(' ');
  await page.screenshot({path:path.join(out,'umbral-battle.png')});
  await page.keyboard.press('i');
  await page.getByRole('button',{name:'Volver al juego'}).waitFor();
  await page.screenshot({path:path.join(out,'umbral-inventory.png')});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Volver al juego'}).click();
  await page.screenshot({path:path.join(out,'umbral-mobile.png')});
  await page.keyboard.press('Escape');
  await page.getByText('PARTIDA EN PAUSA').waitFor();
  await page.getByRole('button',{name:'Guardar y volver al inicio'}).click();
  await page.getByRole('button',{name:/Continuar/}).waitFor();
  await page.reload({waitUntil:'networkidle'});
  await page.locator('flt-semantics-placeholder').evaluate(el=>el.click());
  await page.getByRole('button',{name:/Continuar/}).waitFor({timeout:30000});
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('PASS: web home, movement, gate, portal, map, combat, inventory, portrait and persisted reload.');
  await browser.close();
})().catch(e => {console.error(e);process.exit(1);});
